### ISSUE TITLE
This project appears to be out of date with respect to google's oauth/calendar requirements

### ISSUE THREAD

**Issue by TobyHFerguson** [kidd/org-gcal.el#58]
I tried to follow the instructions today to setup `org-gcal`, but google's workflow for oauth seems to be more stringent than when this project was initially set up. Google now requires that the use of the calendar API setup an OAuth consent screen, hosted on a trusted domain. Unless I'm misreading the `org-gcal` documentation this requirement and screen aren't covered in those docs.

What I expect: A clear explanation of how to setup the OAuth consent screen for `org-gcal`

**Comment by telotortium** [comment]
Can you tell me what exactly you're seeing? I don't think org-gcal should be subject to restrictions on OAuth scopes (see https://support.google.com/cloud/answer/9110914#restricted-scopes), since it doesn't use the Gmail or Drive scopes in question.

**Comment by suiokami** [comment]
Under APIs & Services > OAuth consent screen > "Scopes for Google API's" it reads the following:


"Because you've added a sensitive scope, your consent screen requires verification by Google before it's published. "

And beneath that:

	../auth/calendar 	
	../auth/calendar.events 	
	../auth/calendar.events.readonly 	
	../auth/calendar.readonly 

 each are marked with a ! which specifies:
Use of this API scope will be restricted until it is approved.

Only
  	../auth/calendar.settings.readonly  
escapes this treatment

**Comment by suiokami** [comment]
On the same settings screen it reads:
 OAuth verification

> To protect you and your users, your consent screen and application may need to be verified by Google. Verification is required if your app is marked as Public and at least one of the following is true:

-     Your app uses a sensitive and/or restricted scope
-     Your app displays an icon on its OAuth consent screen
-     Your app has a large number of authorized domains
-     You have made changes to a previously-verified OAuth consent screen

So somehow, somewhere, the 'app' has been marked **Public**?

**Comment by TobyHFerguson** [comment]
This workflow is different than what was described on the org-gcal site (no
surprise! I'm sure Google updates its workflow whenever it chooses to). I
simply ignored the idea of getting google to verify anything ... but the
scopes do say you need to get this verification done, as I understand it.

toby | +1 408 386 9343

**Comment by joostkremers** [comment]
I tried setting up `org-gcal` the other day and ran into the same problem. I haven't been able to create the necessary credentials.

> So somehow, somewhere, the 'app' has been marked **Public**?

Looks like. I've looked around on the Google Developers Console, but I haven't found any way to change this.

**Comment by jchkoch** [comment]
I have been using org-gcal for some years now and it continues to work for me. I followed the credential instructions in the README some years ago which seems to still work fine. One note that I should mention when I got a new laptop (and ran my emacs config) the first time I ran any of the org-gcal commands (i.e. org-gcal-sync or org-gcal-fetch) I had to paste a one-time security code into the emacs minibuffer. This happened earlier (around June/July) of this year.

Hopefully this helps some as another perspective on this issue. Be happy to give more information as to what my google api credential setup is if there is interest. Great project!!!

**Comment by EdGrrr** [comment]
I had this problem as well, with org-gcal-sync rainsing a 401 error.

The fix for me was to remove the org-gcal folder in my .emacs.d folder, which must have contained some old verification data?

When running org-gcal-sync for the first time, emacs opens a web-browser, which then asks you to give permission to your new 'app'. The app does not have to be verified by google. If you leave the app unverified, you just get an unsafe webpage warning, which you can bypass. Following the authentication steps from googel, this will eventually give you a key to paste into the minibuffer.

(I am using emacs 26.3 in ubuntu 18.04)

**Comment by Jassob** [comment]
I suffered from the same issue as the OP, but resolved it by following @EdGrrr's advice and remove the token file.

If that approach works for the OP I vote for closing this issue and maybe add some troubleshooting information about this edge case?

**Comment by nhmacuk** [comment]
Sadly @EdGrrr solution doesn't seem to work for me as it did for @Jassob:
```(org-gcal-request-token)``` takes me to the website, but it doesn't let me through:

_This app isn't verified
This app hasn't been verified by Google yet. Only proceed if you know and trust the developer.
If you’re the developer, submit a verification request to remove this screen._
![image](https://user-images.githubusercontent.com/44981227/71685532-d892ce00-2d98-11ea-8981-1adce23e8678.png)

I have removed the org-gcal directory and have a name in my OAuth Conscent screen settings. It used to work a few months ago, but I hadn't noticed the errors before until I saw it had stopped fetching events.
![image](https://user-images.githubusercontent.com/44981227/71685411-85208000-2d98-11ea-9b42-cccdf694ea98.png)
![image](https://user-images.githubusercontent.com/44981227/71685447-a1bcb800-2d98-11ea-8dce-00a6de5b10c6.png)

trying to ```(org-gcal-fetch-buffer)``` would result in the 403 error mentioned in earlier issues (i think from google rejecting access because the token is expired?): 
```org-gcal-sync-buffer: error: (error Got error 403: (error http 403))
[error] request--callback: peculiar error: 403
[error] request-default-error-callback: https://www.googleapis.com/calendar/v3/calendars/[redacted]@import.calendar.google.com/events/_[redacted] error
(error http 403)```

**Comment by EdGrrr** [comment]
Click on the 'advanced' menu at the warning screen - that should then let you use the app, even though it is not verified (presumably you trust yourself :-) )

**Comment by nhmacuk** [comment]
Haha oops, thanks @EdGrrr. I now got a new token and pasted in minibuffer. However upon fetching with (org-gcal-fetch-buffer) Emacs answers with 403 for each event, and the missing calendar events from my Google calendar were not fetched into the buffer.

**Comment by joostkremers** [comment]
Just FYI: I managed to get `org-gcal` working with the updated instructions. Thanks!
