### ISSUE TITLE
Migrate to using auth-source for holding credentials

### ISSUE THREAD

**Issue by telotortium** [kidd/org-gcal.el#79]
Currently the various credentials needed by `org-gcal` are stored in `org-gcal-token-plist`, which is serialized to `org-gcal-token-file`. However, there are several disadvantages to this format:

- Only supports one OAuth `client_id`/`client_secret`, which means it's impossible to use `org-gcal` with more than one account.
- Credentials on disk are unencrypted.

Instead, move to the auth-source library, which can handle both of these cases.

**Comment by kidd** [comment]
Braindump from 2018:

there's oauth2.el in melpa, but unfortunately I never could make it properly work. epa is kinda clunky and IIRC oauth2.el doesn't properly work fine with the encrypted plstore lib that is supposed to save encrypted values when using async http calls. 

That said, since this recent post: https://www.bytedude.com/gpg-in-emacs , I'm tempted to give it another shot as  maybe I was just configuring the whole thing in a wrong way.

**Comment by telotortium** [comment]
See #14. I wouldn't want to remove the `deferred` dependency, though, because the Calendar API requires some sophisticated handling to its responses, including conditional retries, that would be a pain to write and maintain with a pure callback API. Also, the oauth2.el library only works with `url-retrieve`, not `request` (means you can't avoid the bugs of `url-retrieve`), and uses synchronous requests that you can't avoid.

(In the future, it would be nice to move to something like https://github.com/chuntaro/emacs-async-await that uses Emacs' generator support, but that's a much smaller win.)

**Comment by kidd** [comment]
I agree url-retrieve is bad in its own way.  

It sucks there's a theoretical "proper support" for all the pieces that we need in standard emacs but it's so difficult to make them match that reality pushes to either 'roll-your-own-thing' or use yet-another-http-lib instead of using/improving them.

But I guess you're right. Just wanted to raise it again in case something had changed since 2018.

  :+1:

**Comment by darth10** [comment]
I was looking at using `auth-source` with `org-gcal` and came across this issue.
How about this approach?
1. Store the OAuth `client_id` and `client_secret` using `auth-source`.
1. Try to read access and refresh token from `auth-source`. If the tokens aren't present, create them using `client_id` and `client_secret`.

This approach can be extended to multiple accounts as well.
If you guys are happy with this approach, I'll gladly give it a go and send a PR.

**Comment by ccrusius** [comment]
I have been using https://github.com/ccrusius/auth-source-xoauth2 to interface with Gmail for a few years now. Gnus is fine with it, and has no knowledge of what's going on behind the scenes. So it seems to do what you want - I'd love seeing org-gcal work with it. Contributions to the library to make that happen would be gladly accepted.

**Comment by telotortium** [comment]
Moving to another implementation - see #191.
