### ISSUE TITLE
issues pushing entries to google calendar

### ISSUE THREAD

**Issue by MarinosK** [kidd/org-gcal.el#85]
Hello, 
my setup is absolutely OK insofar as fetching entries from google is concerned. I have problem pushing, tho - I'm not entirely sure if that's because I fail to understand what exactly to do or due to some bug. 

with something like that:

```
* testing local
<2020-05-09 Sat 10:00-11:00>
```

after `org-gcal-post-at-point` I get `Wrong type argument: fixnump, nil`

with this

```
* testing local
:org-gcal:
<2020-05-09 Sat 10:00-11:00>
:END:
```
I get this error

```
(error http 404)

Status code: 404
(error http 404)

deferred error : (error "Got error 404: (error http 404)")
user-error: Minibuffer window is not active
```

with something like that

```
* testing local
:PROPERTIES:
:ETag:     ""
:calendar-id: MY_CAL_ID
:ID:       MY_ID
:END:
:org-gcal:
<2020-05-09 Sat 10:00-11:00>
:END:
```
I get 

```
ETag stale - will overwrite this entry with event from server.
Received HTTP 412
ETag stale - will overwrite this entry with event from server.
```
and then the entire entry is in my file is swapped another one that already exists in google cal.

This does not seem to be the intended behaviour to me. 

Thanks in advance for the help

**Comment by telotortium** [comment]
Hi, currently `org-gcal-post-at-point` must find both some timestamp (either via `SCHEDULED` or the `:org-gcal:` drawer) and the `:calendar-id:` property in order to create an event. On the other hand, if you specify an ID and also an ETag, you're telling `org-gcal` that the heading should be kept in sync with the event of the same ID on the server, which means that the org-gcal heading will be overwritten if the event on the server has changed (i.e., the ETag the client send to the Calendar API is different than the ETag the server is storing currently).

The ETag issue should be documented better, and `org-gcal-post-at-point` should be able to fill in sensible default values for the event time and calendar ID.

**Comment by maikol-solis** [comment]
Hi! 

I have the same error with this entry 

```
*  TEST ENTRY
SCHEDULED: <2020-06-10 Wed 16:00>
```

In the Message buffer appear this

```
[error] request--callback: peculiar error: 404
[error] request-default-error-callback: https://www.googleapis.com/calendar/v3/calendars/nil/events error
org-gcal::Status code: 404 - (error http 404)

deferred error : (error "Got error 404: (error http 404)")
Updating buffer list...done
Commands: m, u, t, RET, g, k, S, D, Q; q to quit; h for help 
```

On the other side, fetching events work fine. 

Thanks for the help.
