### ISSUE TITLE
error fetching non-ascii characters

### ISSUE THREAD

**Issue by limaco** [kidd/org-gcal.el#94]
when google calendar is configured in spanish, whenever an accent is present it's not fetched as utf-8

ie-> saturday/sábado

:org-gcal:
<2020-08-08 s\341 . 13:00-14:00>
:END:

emacs asking for coding system

![Anotación 2020-07-01 223723](https://user-images.githubusercontent.com/6970073/86294292-2b383000-bbec-11ea-9333-9868ce5ec582.png)

**Comment by limaco** [comment]
Just in the properties, though

            character:   (displayed as  ) (codepoint 4194273, #o17777741, #x3fffe1)
              charset: eight-bit (Raw bytes 128-255)
code point in charset: 0xE1
               syntax: w 	which means: word
             category: L:Left-to-right (strong)
             to input: type "C-x 8 RET 3fffe1"
          buffer code: #xE1
            file code: not encodable by coding system utf-8
              display: no font available

**Comment by telotortium** [comment]
Can you check if this happens if you configure Google Calendar to English but leave your Org mode configuration the same? I don't think the code reads the weekday names from Calendar, but rather uses Emacs to format the dates.

I tried to reproduce this by running `(setq system-time-locale "es_ES.UTF-8")` in Emacs, and then running `(format-time-string "%a" (encode-time '(0 0 12 8 8 2020 nil nil t)))`. This returns `"sáb"` on my system. I even ran `org-gcal-fetch` with `system-time-locale` set, and it successfully inserted dates with Spanish weekday names into my Org mode buffers.

Can you check your system locale (if you're on macOS/Linux, run the `locale` command in the terminal)? I also have `buffer-file-coding-system` set to `utf-8-unix` in Emacs - what do you have?

**Comment by limaco** [comment]
Ok, so it seems to be a windows related issue:
there is a beta option to use unicode for non-compatible programs:
![kidd2](https://user-images.githubusercontent.com/6970073/89778736-eb773900-db05-11ea-880c-74883598d096.png)
once unchecked, everything seems ok:
![captura_kidd](https://user-images.githubusercontent.com/6970073/89778775-fa5deb80-db05-11ea-8980-741142176ec8.png)
